name: Libs.Quartz.DependencyInjection (NuGet)

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  pack-push:
    env:
      CAMINHO_PROJETO: ./Libs.Quartz/Libs.Quartz.DependencyInjection/Libs.Quartz.DependencyInjection.csproj

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET 5
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.*

    - name: Geração do package
      run: dotnet pack ${{ env.CAMINHO_PROJETO }} -c Release -o out

    - name: Push no NuGet
      run: |
        cd out
        dotnet nuget push *.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source ${{ secrets.NUGET_SERVER }} --skip-duplicate
